-- CreateTable
CREATE TABLE "ProductVariant" (
    "id" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "sku" TEXT NOT NULL,
    "price" DECIMAL(10,2) NOT NULL,
    "stockQuantity" INTEGER NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "images" TEXT[] NOT NULL,
    "position" INTEGER NOT NULL DEFAULT 0,
    "optionKey" TEXT NOT NULL,

    CONSTRAINT "ProductVariant_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ProductOption" (
    "id" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "position" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "ProductOption_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ProductOptionValue" (
    "id" TEXT NOT NULL,
    "optionId" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "position" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "ProductOptionValue_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ProductVariantOptionSelection" (
    "variantId" TEXT NOT NULL,
    "optionId" TEXT NOT NULL,
    "optionValueId" TEXT NOT NULL,

    CONSTRAINT "ProductVariantOptionSelection_pkey" PRIMARY KEY ("variantId","optionId")
);

-- CreateTable
CREATE TABLE "ProductVariantSpecification" (
    "id" TEXT NOT NULL,
    "variantId" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "unit" TEXT,
    "position" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "ProductVariantSpecification_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ProductVariant_sku_key"
ON "ProductVariant"("sku");

-- CreateIndex
CREATE UNIQUE INDEX "ProductVariant_productId_optionKey_key"
ON "ProductVariant"("productId", "optionKey");

-- CreateIndex
CREATE INDEX "ProductVariant_productId_position_idx"
ON "ProductVariant"("productId", "position");

-- CreateIndex
CREATE INDEX "ProductVariant_productId_isActive_position_idx"
ON "ProductVariant"("productId", "isActive", "position");

-- CreateIndex
CREATE UNIQUE INDEX "ProductOption_productId_code_key"
ON "ProductOption"("productId", "code");

-- CreateIndex
CREATE INDEX "ProductOption_productId_position_idx"
ON "ProductOption"("productId", "position");

-- CreateIndex
CREATE UNIQUE INDEX "ProductOptionValue_optionId_value_key"
ON "ProductOptionValue"("optionId", "value");

-- CreateIndex
CREATE UNIQUE INDEX "ProductOptionValue_id_optionId_key"
ON "ProductOptionValue"("id", "optionId");

-- CreateIndex
CREATE INDEX "ProductOptionValue_optionId_position_idx"
ON "ProductOptionValue"("optionId", "position");

-- CreateIndex
CREATE INDEX "ProductVariantOptionSelection_optionValueId_optionId_idx"
ON "ProductVariantOptionSelection"("optionValueId", "optionId");

-- CreateIndex
CREATE UNIQUE INDEX "ProductVariantSpecification_variantId_key_key"
ON "ProductVariantSpecification"("variantId", "key");

-- CreateIndex
CREATE INDEX "ProductVariantSpecification_variantId_position_idx"
ON "ProductVariantSpecification"("variantId", "position");

-- AddForeignKey
ALTER TABLE "ProductVariant"
ADD CONSTRAINT "ProductVariant_productId_fkey"
FOREIGN KEY ("productId")
REFERENCES "Product"("id")
ON DELETE CASCADE
ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ProductOption"
ADD CONSTRAINT "ProductOption_productId_fkey"
FOREIGN KEY ("productId")
REFERENCES "Product"("id")
ON DELETE CASCADE
ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ProductOptionValue"
ADD CONSTRAINT "ProductOptionValue_optionId_fkey"
FOREIGN KEY ("optionId")
REFERENCES "ProductOption"("id")
ON DELETE CASCADE
ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ProductVariantOptionSelection"
ADD CONSTRAINT "ProductVariantOptionSelection_variantId_fkey"
FOREIGN KEY ("variantId")
REFERENCES "ProductVariant"("id")
ON DELETE CASCADE
ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ProductVariantOptionSelection"
ADD CONSTRAINT "ProductVariantOptionSelection_optionValueId_optionId_fkey"
FOREIGN KEY ("optionValueId", "optionId")
REFERENCES "ProductOptionValue"("id", "optionId")
ON DELETE CASCADE
ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ProductVariantSpecification"
ADD CONSTRAINT "ProductVariantSpecification_variantId_fkey"
FOREIGN KEY ("variantId")
REFERENCES "ProductVariant"("id")
ON DELETE CASCADE
ON UPDATE CASCADE;

-- Backfill one default variant for every existing product.
--
-- Product.sku is already globally unique, so copying it into a new,
-- initially empty ProductVariant table is collision-free.
--
-- Prisma's cuid() default is generated by Prisma Client rather than
-- PostgreSQL. Existing rows therefore receive a deterministic migration
-- ID derived from their Product.id.
INSERT INTO "ProductVariant" (
    "id",
    "productId",
    "sku",
    "price",
    "stockQuantity",
    "isActive",
    "images",
    "position",
    "optionKey"
)
SELECT
    'pv_default_' || product."id",
    product."id",
    product."sku",
    product."price",
    product."stockQuantity",
    product."isActive",
    ARRAY[]::TEXT[],
    0,
    'default'
FROM "Product" AS product;
